input.onButtonEvent(Button.A, input.buttonEventClick(), function () {
    music.playMelody("C C5 D B E A F G ", 120)
    music.playMelody("G F A E B D C5 C ", 120)
    music.playTone(131, music.beat(BeatFraction.Half))
    music.playTone(147, music.beat(BeatFraction.Half))
    music.playTone(165, music.beat(BeatFraction.Half))
    music.playTone(175, music.beat(BeatFraction.Half))
    music.playTone(196, music.beat(BeatFraction.Half))
    music.playTone(220, music.beat(BeatFraction.Half))
    music.playTone(247, music.beat(BeatFraction.Half))
    music.playMelody("C E D F E G F A ", 120)
    music.playMelody("G B A C5 B A G F ", 300)
    music.playMelody("E D C D E F G A ", 300)
    music.playMelody("C B E G F E A C ", 300)
})
